services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: habit-tracker-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: habittracker
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - habit-tracker-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/habittracker --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Mongo Express Admin Panel
  mongo-express:
    image: mongo-express:1.0.0
    container_name: habit-tracker-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - habit-tracker-network

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: habit-tracker-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password123@mongodb:27017/habittracker?authSource=admin
      SPRING_DATA_MONGODB_DATABASE: habittracker
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - habit-tracker-network
    healthcheck:
      test: "curl -f http://localhost:8080/actuator/health || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # React Frontend (Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: habit-tracker-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - habit-tracker-network

volumes:
  mongodb_data:

networks:
  habit-tracker-network:
    driver: bridge